# 不可恢复错误

使用 panic! 宏是创建不可恢复的错误最简便的用法.

```rust
fn main() {
    panic!("error!");
    println!("here");
}
```

同时还有一些常见的宏可导致不可恢复的错误

## 断言

```rust
assert!(1 == 2);
assert_eq!(1, 2); // 等效于 assert!(1 == 2)
```

## 未实现的代码

```rust
fn add(a: u32, b: u32) -> u32 {
    unimplemented!()
}

fn main() {
    println!("{}", add(1, 2));
}
```

## 不应当被访问的代码

程序代码中存在一些分支, 程序的开发这认为这些分支永远不应该被触发, 如果触发了这些分支, 则很可能是上游代码出现了问题:

```rust
fn divide_by_three(x: u32) -> u32 { // one of the poorest implementations of x/3
    for i in 0.. {
        if 3*i < i { panic!("u32 overflow"); }
        if x < 3*i { return i-1; }
    }
    unreachable!();
}
```
