# 自定义错误与问号表达式

## 问号表达式

许多时候, 尤其是在我们编写库的时候, 不仅仅希望获取错误, 更希望错误可以在上下文中的进行传递. 有一种简便的方式可以传递错误: 使用问号表达式. 当函数的错误类型与当前错误的类型相同时, 使用 ? 可以直接将错误传递到函数外并终止函数执行.

```rust
fn foo() -> Result<T, E> {
    let x = bar()?; // bar 的错误类型需要与 foo 的错误类型相同
    ...
}
```

? 的作用是将 Result 枚举的正常的值直接取出, 如果有错误就将错误返回出去.

## 创建自定义的错误

```rust
#[derive(Debug, PartialEq, Clone, Copy, Eq)]
pub enum Error {
    IO(std::io::ErrorKind),
}

impl From<std::io::Error> for Error {
    fn from(error: std::io::Error) -> Self {
        Error::IO(error.kind())
    }
}

fn do_read_file() -> Result<(), Error>{
    let data =  std::fs::read("/tmp/foo")?;
    let data_str = std::str::from_utf8(&data).unwrap();
    println!("{}", data_str);
    Ok(())
}

fn main() {
    do_read_file().unwrap();
}
```
